// <auto-generated />
using System;
using Labaxurias.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labaxurias.Infrastructure.Migrations
{
    [DbContext(typeof(LabaxuriasDbContext))]
    [Migration("20260714221045_AddIsActiveToCatalog")]
    partial class AddIsActiveToCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Labaxurias.Infrastructure.Domain.Entities.Medium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mediums");
                });

            modelBuilder.Entity("Labaxurias.Infrastructure.Domain.Entities.QueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCalled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SessionEntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SpiritualGuideId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionEntityId");

                    b.HasIndex("SpiritualGuideId");

                    b.ToTable("QueueItems");
                });

            modelBuilder.Entity("Labaxurias.Infrastructure.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Labaxurias.Infrastructure.Domain.Entities.SessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpiritualGuideId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SpiritualGuideId");

                    b.ToTable("SessionEntities");
                });

            modelBuilder.Entity("Labaxurias.Infrastructure.Domain.Entities.SpiritualGuide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MediumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediumId");

                    b.ToTable("SpiritualGuides");
                });

            modelBuilder.Entity("Labaxurias.Infrastructure.Domain.Entities.QueueItem", b =>
                {
                    b.HasOne("Labaxurias.Infrastructure.Domain.Entities.SessionEntity", "SessionEntity")
                        .WithMany("QueueItems")
                        .HasForeignKey("SessionEntityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Labaxurias.Infrastructure.Domain.Entities.SpiritualGuide", "SpiritualGuide")
                        .WithMany()
                        .HasForeignKey("SpiritualGuideId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SessionEntity");

                    b.Navigation("SpiritualGuide");
                });

            modelBuilder.Entity("Labaxurias.Infrastructure.Domain.Entities.SessionEntity", b =>
                {
                    b.HasOne("Labaxurias.Infrastructure.Domain.Entities.Session", "Session")
                        .WithMany("SessionEntities")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labaxurias.Infrastructure.Domain.Entities.SpiritualGuide", "SpiritualGuide")
                        .WithMany()
                        .HasForeignKey("SpiritualGuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("SpiritualGuide");
                });

            modelBuilder.Entity("Labaxurias.Infrastructure.Domain.Entities.SpiritualGuide", b =>
                {
                    b.HasOne("Labaxurias.Infrastructure.Domain.Entities.Medium", "Medium")
                        .WithMany()
                        .HasForeignKey("MediumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medium");
                });

            modelBuilder.Entity("Labaxurias.Infrastructure.Domain.Entities.Session", b =>
                {
                    b.Navigation("SessionEntities");
                });

            modelBuilder.Entity("Labaxurias.Infrastructure.Domain.Entities.SessionEntity", b =>
                {
                    b.Navigation("QueueItems");
                });
#pragma warning restore 612, 618
        }
    }
}
